#!/usr/bin/env python

# The purpose of this file is to split a single file containing sets of 
# problems generated by eqn_generator.lp
# the expected input format is:
#
#   Answer:.
#   holds(blah, blah....)
#   holds(blah, blah....)
#   ...
#   Answer:.
#   holds(blah, blah....)

import sys

# XXX: not checking first argument, I assume its file name of problems to separate into files
opened_file = file(sys.argv[1], 'r') 
inputs = opened_file.read()
for index, st in enumerate(inputs.split('Answer:.')):
    if st == '': # splitting on Answer, produces an empty string
        continue
    output_file = file('probs/'+str(index) + '.prob', 'w')
    output_file.write(st)
    output_file.close()
opened_file.close()


    # need to save each in a separate file

    # need to call it number.prob or something
    # then need to compute all answer sets for each file in number.prob
    # bash script calls all_solutions.lp for each number.lp instance
    # and calls visualizer code, 
    # visualizer code needs to be improved to save results in permanent storage,
    # visualizer needs to be improved to save all answer sets (different solutions) as one problem


