#!/bin/bash
# this script is used to create a set of files, each one corresponding to one 
# problem generated by eqn_generator.lp


# clear directories
rm probs/*
rm soln/*
rm gen_prob/*
rm json_prob/*

## generate problems
CMD='clingo eqn_generator.lp --project -n 50 --sign-def=3 --seed='$RANDOM
$CMD | tr ' ' '\n' | grep "Answer\|holds" | grep "Answer\|_time(0,1)" | sed -e 's/$/\./g'> generated_problems.prob
python get_all_soln.py generated_problems.prob

# for each problem generate all solutions and optimal solution
for p in $(ls probs/); do
    clingo all_solutions.lp "probs/$p" --project -n 0 "--outf=2" > "soln/all_soln_for_$p"
    clingo eqn_generator.lp "probs/$p" "--outf=2" > "soln/optimal_soln_for_$p"
    python merge_solutions.py "soln/all_soln_for_$p" "soln/optimal_soln_for_$p" "gen_prob/$p.json"
done

# each file contains all solutions of equal length for a given problem
# load into visualizer
for soln_file in $(ls gen_prob/); do
    cat gen_prob/$soln_file | python totally_new_visualizer.py "--json_output=true" > json_prob/$soln_file.json
    #cat gen_prob/$soln_file | python totally_new_visualizer.py > json_prob/$soln_file
done

